spring:
  #  jpa:
  #    hibernate:
  #      ddl-auto: none
  #
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  management:
    security:
      enabled: false
    endpoints:
      enabled-by-default: true
      web:
        exposure:
          include: '*'
    endpoint:
      health:
        show-details: always
    health:
      probes:
        enabled: true
      diskspace:
        enabled: true
      ping:
        enabled: true
      livenessstate:
        enabled: true
      readinessstate:
        enabled: true