service:
  ChatBootApi:
#    url: ${CHATBOOT_API_URL}
#    key: ${CHATBOOT_API_KEY}
#    bid: ${CHATBOOT_API_BID}
#    uid: ${CHATBOOT_API_UID}
    url: http://api.brainshop.ai
    key: m7ZM9EjYVls7QD52
    bid: 164660
    uid: 85631

spring:
  #  jpa:
  #    hibernate:
  #      ddl-auto: none
  #
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  management:
    security:
      enabled: false
    endpoints:
      enabled-by-default: true
      web:
        exposure:
          include: '*'
    endpoint:
      health:
        show-details: always